# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Macaulay Business Club
# Description of the Site
description: The Macaulay Business Club website
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.vox-cdn.com/thumbor/Q7_74k0zUmVCID7lnfaxKMuSaVU=/0x0:4000x2667/1200x800/filters:focal(1680x1014:2320x1654)/cdn.vox-cdn.com/uploads/chorus_image/image/65027193/shutterstock_788608396.0.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: themacaulaybusinessclub@gmail.com
facebook_username: MacaulayBusinessClub
twitter_username: 
instagram_username: macaulaybusinessclub
linkedin_username: macaulaybusinessclub
github_username:  themacaulaybusinessclub
youtube_channel_id: UCwjLK6ejl-yAjJhStPzX_eA
reddit_username: 
behance_username: 
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: mbc

# Name of the Author
author-name: themacaulaybusinessclub
# URL for the Image of the Author
author-image: assets/images/logo.png
# 60 Words About the Author
author-about: Macaulay Business Club is devoted to creating a collaborative pre-professional community that can share informative experiences. We engage in a variety of activites, such as professional development events, technical workshops, and company tours to give students a taste of the real-world. We want to help build a better future for our members and becoming a member of one of our committees where we encourage mobility is the first step.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: blog/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
